global:
  # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  scrape_interval: 15s
  # Evaluate rules every 15 seconds. The default is every 1 minute.
  evaluation_interval: 15s

scrape_configs:
  # Self-monitoring
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
  - job_name: "grafana"
    static_configs:
      - targets: ["localhost:3000"]

  # Fetch from node_exporter on all of the EC2 hosts
  - job_name: "node"
    ec2_sd_configs:
      - region: us-east-1
        port: 9100
        refresh_interval: 1m
        filters:
          - name: instance-state-name
            values: ["running"]
    relabel_configs:
      - source_labels: ["__meta_ec2_tag_Name"]
        target_label: "instance"
      - source_labels: ["__meta_ec2_tag_role"]
        target_label: "role"
