apiVersion: v1
kind: Service
metadata:
  name: game-manager
  labels:
    app: {{ template "rpsls-game.name" . }}
    chart: {{ template "rpsls-game.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.service.grpcPort }}
      targetPort: grpc
      protocol: TCP
      name: grpc
  selector:
    app: {{ template "rpsls-game.name" . }}
    release: {{ .Release.Name }}
